### ISSUE TITLE
Cattle

### ISSUE THREAD

**Issue by pedromoraesh** [burnpiro/farm-animal-tracking#6]
Hi guys,

First, I would like to say you did a GOOD JOB in this repo!

Then, I have a few questions: 

- I have cattle data, the first step so is to put that data into the data/cropped_images/(id)?;
- Can I train only the siamese network for feature extraction? and then only have a 64D output. I already have the images cropped by themselves because they were detected from another network and I only want to extract particular features for CattleRe-ID;
- Can I change the code to output more dimensions? e.g 128,256...

I have about 60K cattle images of 100 classes. I think working with 128D or 256D would fit better to my problem.

Thanks in advance.

**Comment by burnpiro** [comment]
Hi,

Sorry for the late response but I'm really busy lately. Regarding your questions:
@1 
Yes, you can put your train data into `data/cropped_images/{id}/*.{jpg/png}` and then edit the path in train script 

[https://github.com/burnpiro/farm-animal-tracking/blob/main/train_siamese.py#L33](https://github.com/burnpiro/farm-animal-tracking/blob/main/train_siamese.py#L33)

To `data/cropped_images`

You can also create `data/cropped_images/train` and `data/cropped_images/test` folders and split your data (and modify paths in `train_siamese.py` [line 33](https://github.com/burnpiro/farm-animal-tracking/blob/main/train_siamese.py#L33) and `test_siamese.py` [line 73](https://github.com/burnpiro/farm-animal-tracking/blob/main/test_siamese.py#L73). That is useful when you want to generate embedding visualization later one with `generate_siamese_emb_space.py`.

@2 and @3
Yes, you can train only the siamese network if you have a working detector. Yo change how the network looks like you can modify 
[https://github.com/burnpiro/farm-animal-tracking/blob/main/model/siamese/model_generator.py#L33](https://github.com/burnpiro/farm-animal-tracking/blob/main/model/siamese/model_generator.py#L33)

And just set last layer to be a desired size. Input size is set in `config,py` file.

**Comment by pedromoraesh** [comment]
Thanks, @burnpiro !

I will try it with your tips.
